### ISSUE TITLE
lfortran branch test error

### ISSUE THREAD

**Issue by lishchgithub** [StarGate01/Full-Stack-Fortran#11]
When I try the lfortran test example, got a issue that:
Traceback (most recent call last):
  File "/app/conda/bin/lfort", line 3, in <module>
    from lfortran.cli import main
  File "/app/conda/lib/python3.7/site-packages/lfortran/__init__.py", line 1, in <module>
    from .ast.utils import src_to_ast
  File "/app/conda/lib/python3.7/site-packages/lfortran/ast/__init__.py", line 15, in <module>
    from .utils import (src_to_ast, parse_file, dump, print_tree, print_tree_typed,
  File "/app/conda/lib/python3.7/site-packages/lfortran/ast/utils.py", line 7, in <module>
    from ..parser.parser import antlr_parse
  File "/app/conda/lib/python3.7/site-packages/lfortran/parser/parser.py", line 21, in <module>
    from .fortranLexer import fortranLexer
  File "/app/conda/lib/python3.7/site-packages/lfortran/parser/fortranLexer.py", line 403, in <module>
    class fortranLexer(Lexer):
  File "/app/conda/lib/python3.7/site-packages/lfortran/parser/fortranLexer.py", line 405, in fortranLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/app/conda/lib/python3.7/site-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/app/conda/lib/python3.7/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).
Seems Like Lfortran in conada is disabled.
I also tried run lfort single, also get the same problem.

**Comment by StarGate01** [comment]
Hi, I have not continued to work on the LFortran branch since I got gfortran working - it was one of the many avenues I explored which did not end up working. 

However, LFortran has been under active development since, so a second look at it might be something to consider. Also see https://github.com/StarGate01/Full-Stack-Fortran/issues/7#issuecomment-1094346218 .
